### ISSUE TITLE
Echelon MEP Problem - Became unavailable on Power return

### ISSUE THREAD

**Issue by nean-and-i** [jnxxx/homeassistant-dabblerdk_powermeterreader#8]
When sun is shining and solar panels are producing power and the amount of power consumed is lower than produced aka power returned to grid, then the MEP readings stop to work and the integration triggers a problem.

<img width="559" alt="ha-mep01" src="https://user-images.githubusercontent.com/1310469/215987090-4a2135d4-7f47-4a3f-9adb-98feeb2e4372.png">

The sensor values gets stuck at the previous reading until the integration is reloaded.
The only suspicious Warning I could find in the logs are lines starting like: 

```log
L1_Fwd_W + L2_Fwd_W + L3_Fwd_W does not equal Fwd_W (499 != 142), sticking to previous values
...
L1_Fwd_W + L2_Fwd_W + L3_Fwd_W does not equal Fwd_W (502 != 142), sticking to previous values
```

As a workaround I had to create an automation that triggers a reload of the integration whenever the problem binary sensor switched to active to get the problem cleared and at least a fresh reading.

```yaml
alias: echelon reload
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.echelon_mep_problem
    to: "on"
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: <device = Echelon>
mode: single
```

Are there any data evaluation checks in place that probably do not consider this use case?
The Integration works great as long no power is returned to the grid.
